### ISSUE TITLE
Convert hexwall into a package?

### ISSUE THREAD

**Issue by pkq** [mitchelloharawild/hexwall#1]
I've been mulling the idea of something similar for a few weeks now, so thanks for putting this together! Have you considered turning this into a proper package? Even with just the one function, I think it'd be worthwhile, and could be done pretty easily with `usethis` (and friends). Would you be interested in a PR to that effect?

**Comment by mitchelloharawild** [comment]
I have considered making it a package (the code is written in a way to make a package from it trivially), however I do not see the need for a package yet.

I was first planning to make it a gist, however using a repo allows me to describe the function with the README, and help users try the function for themselves. As it is simple to setup the function already, I actually think a single-function package is harder for users to setup.

In-fact, the current usage guide could be simplified to running
```r
source("https://raw.githubusercontent.com/mitchelloharawild/hexwall/master/hexwall.R")
```
Except I wanted to discourage this because sourcing files directly from the web can be dangerous.

If the script had more functionality, I can see this being developed into an R package. For example, if a repository was constructed to organise and store R-specific hexagon stickers (similar to https://github.com/maxogden/hexbin), this package could provide tools to access and combine them.

**Comment by pkq** [comment]
Fair enough. I definitely appreciate the README and that you're not encouraging users to source directly from the web, even though I'm pretty all-in on the idea of packages as "the fundamental units of reproducible R code" as Hadley would say. An R-specific hex sticker repository would be slick! I've long wished there were more R hex stickers on hexbin. At any rate, thanks much for sharing the code!

**Comment by pkq** [comment]
Out of curiosity, do you have any thoughts about the best way to go about creating an R-specific hex sticker repository?

**Comment by mitchelloharawild** [comment]
I think hexbin does it very well, so the best way would probably be to start from their repo.

I would like the meta information to be slightly more informative, to allow for package names, distinguishing between CRAN/Bioconductor/GitHub/Other packages... It would also be nice to store keywords and other information (similar to https://github.com/ggplot2-exts/gallery).

**Comment by pkq** [comment]
Agreed on both counts. Coincidentally, I was just granted collaborator access to hexbin, so I can actually get stickers merged (including you pride sticker 😄), if you know anyone who's been holding off on submitting there given the limited activity in recent months. 

I also [posted an issue](https://github.com/maxogden/hexbin/issues/199) with some initial ideas for additional metadata fields to hexbin itself. Would be great to get your thoughts there, if you're interested. I'm guessing that any changes would be more limited in scope than what the ggplot2 extensions gallery has, but I think it's worth a conversation before getting too far on anything R specific.
